@description('Azure region for resources.')
param location string

@description('Name of the App Service Plan.')
param planName string

@description('Name of the App Service (web app).')
param appName string

@description('SKU for the App Service Plan.')
param planSku string

@description('Resource ID of the Application Insights component.')
param appInsightsId string

@description('Application Insights connection string.')
param appInsightsConnectionString string

@description('Application Insights instrumentation key.')
param appInsightsInstrumentationKey string

@description('Resource ID of the Log Analytics Workspace that receives the App Service diagnostic logs.')
param logAnalyticsWorkspaceId string

@description('SQL connection string used by the API at runtime.')
@secure()
param sqlConnectionString string

@description('Origin allowed to call the API via CORS (the frontend static website).')
param corsAllowedOrigin string

// Free and Shared plans don't support Always On or 64-bit workers.
var isFreeOrShared = startsWith(planSku, 'F') || startsWith(planSku, 'D')

resource appServicePlan 'Microsoft.Web/serverfarms@2024-11-01' = {
  name: planName
  location: location
  kind: 'app'
  sku: {
    name: planSku
  }
}

resource appService 'Microsoft.Web/sites@2024-11-01' = {
  name: appName
  location: location
  kind: 'api'
  // Links the web app to Application Insights in the portal.
  tags: {
    'hidden-link: /app-insights-resource-id': appInsightsId
  }
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    serverFarmId: appServicePlan.id
    httpsOnly: true
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
    siteConfig: {
      netFrameworkVersion: 'v10.0'
      alwaysOn: !isFreeOrShared
      use32BitWorkerProcess: isFreeOrShared
      minTlsVersion: '1.2'
      ftpsState: 'FtpsOnly'
    }
  }
}

// This replaces the app's entire settings collection, so every setting the app needs must be declared here.
resource appSettings 'Microsoft.Web/sites/config@2024-11-01' = {
  parent: appService
  name: 'appsettings'
  properties: {
    ConnectionStrings__CheckMate: sqlConnectionString
    Cors__AllowedOrigins__0: corsAllowedOrigin
    APPLICATIONINSIGHTS_CONNECTION_STRING: appInsightsConnectionString
    APPINSIGHTS_INSTRUMENTATIONKEY: appInsightsInstrumentationKey
    ApplicationInsightsAgent_EXTENSION_VERSION: '~2'
    XDT_MicrosoftApplicationInsights_Mode: 'default'
    XDT_MicrosoftApplicationInsights_BaseExtensions: 'disabled'
    XDT_MicrosoftApplicationInsights_PreemptSdk: 'disabled'
    XDT_MicrosoftApplicationInsights_Java: '1'
    XDT_MicrosoftApplicationInsights_NodeJS: '1'
    APPINSIGHTS_PROFILERFEATURE_VERSION: 'disabled'
    APPINSIGHTS_SNAPSHOTFEATURE_VERSION: 'disabled'
    DiagnosticServices_EXTENSION_VERSION: 'disabled'
    InstrumentationEngine_EXTENSION_VERSION: 'disabled'
    SnapshotDebugger_EXTENSION_VERSION: 'disabled'
    WEBSITE_ENABLE_SYNC_UPDATE_SITE: 'true'
  }
}

resource diagnostics 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = {
  scope: appService
  name: 'logs-to-workspace'
  properties: {
    workspaceId: logAnalyticsWorkspaceId
    logAnalyticsDestinationType: 'Dedicated'
    logs: [
      for category in [
        'AppServiceHTTPLogs'
        'AppServiceConsoleLogs'
        'AppServiceAppLogs'
        'AppServicePlatformLogs'
      ]: {
        category: category
        enabled: true
      }
    ]
  }
}

@description('Default HTTPS URL of the App Service.')
output appServiceUrl string = 'https://${appService.properties.defaultHostName}'

@description('Principal ID of the App Service system-assigned managed identity.')
output principalId string = appService.identity.principalId
